/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNav: typeof import('./src/components/AppNav.vue')['default']
    Background: typeof import('./src/components/Background.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    EpCheck: typeof import('~icons/ep/check')['default']
    EpDownload: typeof import('~icons/ep/download')['default']
    EpPaperclip: typeof import('~icons/ep/paperclip')['default']
    EpPicture: typeof import('~icons/ep/picture')['default']
    EpUploadFilled: typeof import('~icons/ep/upload-filled')['default']
    PageTransition: typeof import('./src/components/PageTransition.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
